fruit1 = input("enter the name of  1 fruit :-")
fruit2 = input("enter the name of  2 fruit :-")
fruit3 = input("enter the name of  3 fruit :-")
fruit4 = input("enter the name of  4 fruit :-")
fruit5 = input("enter the name of  5 fruit :-")
fruit6 = input("enter the name of  6 fruit :-")
fruit7 = input("enter the name of  7 fruit :-")

fruites = ([fruit1],[fruit2],[fruit3],[fruit4],[fruit5],[fruit6],[fruit7])
print(fruites)